name: Coverage Comment
branding:
  icon: "umbrella"
  color: "purple"
description: >
  Publish diff coverage report as PR comment, and create a coverage badge
  to display on the readme.
inputs:
  GITHUB_TOKEN:
    description: >
      A GitHub token to write comments and write the badge to the wiki
      (``github.token``)
    required: true
  COVERAGE_FILE:
    description: >
      Path and filename of the coverage XML file to analyze.
    default: "coverage.xml"
    required: false
  COMMENT_TEMPLATE:
    description: >
      [Advanced] Specify a different template for the comments that will be written on the PR.
    required: false
  DIFF_COVER_ARGS:
    description: >
      [Advanced] Additional args to pass to diff cover (one per line)
    required: false
  BADGE_ENABLED:
    description: >
      Whether or not a badge will be generated and stored.
    default: "true"
    required: false
  BADGE_FILENAME:
    description: >
      Name of the json file containing badge informations stored in the repo
      wiki.
    default: coverage-comment-badge.json
    required: false
  MINIMUM_GREEN:
    description: >
      If the coverage percentage is above or equal to this value, the badge
      will be green.
    default: 100
    required: false
  MINIMUM_ORANGE:
    description: >
      If the coverage percentage is not green and above or equal to this value,
      the badge will be orange. Otherwise it will be red.
    default: 70
    required: false
  MARKER:
    description: >
      Identifier to find the comment in the PR. This will be used to update
      the comment instead of creating a new one.
    default: "<!-- This comment was produced by coverage-comment-action -->"
    required: false
runs:
  using: docker
  image: Dockerfile
  # image: docker://ewjoachim/coverage-comment-action:latest
  env:
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    COVERAGE_FILE: ${{ inputs.COVERAGE_FILE }}
    COMMENT_TEMPLATE: ${{ inputs.COMMENT_TEMPLATE }}
    DIFF_COVER_ARGS: ${{ inputs.DIFF_COVER_ARGS }}
    BADGE_ENABLED: ${{ inputs.BADGE_ENABLED }}
    BADGE_FILENAME: ${{ inputs.BADGE_FILENAME }}
    MINIMUM_GREEN: ${{ inputs.MINIMUM_GREEN }}
    MINIMUM_ORANGE: ${{ inputs.MINIMUM_ORANGE }}
